### ISSUE TITLE
Impossible to spawn a node

### ISSUE THREAD

**Issue by DimitriTimoz** [floneum/floneum#143] opened 2024-02-03 22:43 UTC
**Problem**

Impossible to spawn a node, plugin instantiating failure.
Getting the following when I try to add `Search` Node :

```
  2024-02-03T22:38:41.989527Z ERROR floneum::plugin_search: Failed to insert plugin: import `plugins:main/imports` has the wrong type
    at floneum/floneum/src/plugin_search.rs:108
```
The concerned code [here](https://github.com/floneum/floneum/blob/dce7d300a547a740e3c7d329f9a6f9be54905011/floneum/plugin/src/plugin.rs#L130-L131).

**Steps To Reproduce**

- Build tailwind : `npx tailwindcss -i ./input.css -o ./public/tailwind.css --watch`
- Compile floneum with the debug version : `RUST_LOG=trace cargo run`
- Try to add `Format`, `Contains`, ect nodes
-  Or try to add `Search` node

**Environment:**

- Renderer version: `floneum master`
- Rust version: `1.75.0`
- OS info:  `macOS`

**Questionnaire**

- [X] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment] 2024-02-04 00:21
That is generally caused by a mismatched version between the wit interface used in the floneum binary and the plugins. https://github.com/floneum/floneum/commit/b1366d8b4f053b9b7fb1af21d8ac9d2d81acf3ea rebuilt the plugins to make the versions match. https://github.com/floneum/floneum/commit/05b93a47dda2175c0a141cd3b3e834a554fcbac6 adds a workflow that should keep those up to date in the future. Loading plugins from the local path now works. `floneum-cli clean` should clean the cache that floneum uses for the plugins, but it looks like there is an still an issue with remote plugins

**Comment by ealmloff** [comment] 2024-02-04 00:55
Remote plugins are fixed now. You may need to run `floneum-cli clean` (or wait until the cache refreshes).

I need to add a version number to the plugin metadata. The remote plugins were causing issues because it was loading an older version of the plugin.

**Closed** 2024-02-06 20:40 UTC
Labels: bug, floneum
